-- Seed the launch destination list (Stage 0 list, 46 destinations).
-- Safe to re-run: existing IATA codes are left untouched.

insert into destinations (iata, city, country, slug) values
  ('FAO', 'Faro', 'Portugal', 'faro'),
  ('OPO', 'Porto', 'Portugal', 'porto'),
  ('FNC', 'Funchal', 'Portugal', 'funchal'),
  ('AGP', 'Malaga', 'Spain', 'malaga'),
  ('SVQ', 'Seville', 'Spain', 'seville'),
  ('PMI', 'Palma', 'Spain', 'palma'),
  ('IBZ', 'Ibiza', 'Spain', 'ibiza'),
  ('ALC', 'Alicante', 'Spain', 'alicante'),
  ('MAH', 'Menorca', 'Spain', 'menorca'),
  ('TFS', 'Tenerife South', 'Spain', 'tenerife-south'),
  ('LPA', 'Gran Canaria', 'Spain', 'gran-canaria'),
  ('FUE', 'Fuerteventura', 'Spain', 'fuerteventura'),
  ('ACE', 'Lanzarote', 'Spain', 'lanzarote'),
  ('NCE', 'Nice', 'France', 'nice'),
  ('LYS', 'Lyon', 'France', 'lyon'),
  ('BOD', 'Bordeaux', 'France', 'bordeaux'),
  ('GNB', 'Grenoble', 'France', 'grenoble'),
  ('GVA', 'Geneva', 'Switzerland', 'geneva'),
  ('SZG', 'Salzburg', 'Austria', 'salzburg'),
  ('INN', 'Innsbruck', 'Austria', 'innsbruck'),
  ('GRZ', 'Graz', 'Austria', 'graz'),
  ('TRN', 'Turin', 'Italy', 'turin'),
  ('VRN', 'Verona', 'Italy', 'verona'),
  ('BRI', 'Bari', 'Italy', 'bari'),
  ('CTA', 'Catania', 'Italy', 'catania'),
  ('CAG', 'Cagliari', 'Italy', 'cagliari'),
  ('MLA', 'Malta', 'Malta', 'malta'),
  ('LCA', 'Larnaca', 'Cyprus', 'larnaca'),
  ('PFO', 'Paphos', 'Cyprus', 'paphos'),
  ('HER', 'Heraklion', 'Greece', 'heraklion'),
  ('CHQ', 'Chania', 'Greece', 'chania'),
  ('CFU', 'Corfu', 'Greece', 'corfu'),
  ('RHO', 'Rhodes', 'Greece', 'rhodes'),
  ('KGS', 'Kos', 'Greece', 'kos'),
  ('SKG', 'Thessaloniki', 'Greece', 'thessaloniki'),
  ('PVK', 'Preveza', 'Greece', 'preveza'),
  ('DLM', 'Dalaman', 'Turkey', 'dalaman'),
  ('AYT', 'Antalya', 'Turkey', 'antalya'),
  ('ADB', 'Izmir', 'Turkey', 'izmir'),
  ('RAK', 'Marrakech', 'Morocco', 'marrakech'),
  ('RBA', 'Rabat', 'Morocco', 'rabat'),
  ('AGA', 'Agadir', 'Morocco', 'agadir'),
  ('ALG', 'Algiers', 'Algeria', 'algiers'),
  ('SSH', 'Sharm El Sheikh', 'Egypt', 'sharm-el-sheikh'),
  ('IVL', 'Ivalo', 'Finland', 'ivalo'),
  ('RVN', 'Rovaniemi', 'Finland', 'rovaniemi')
on conflict (iata) do nothing;
